#ifndef settingsPhysics_h
#define settingsPhysics_h


#define PHYSICS_BASE_UPDATE_RATE 120.f
#define PHYSICS_UPDATE_RATE 120.f
#define PHYSICS_SOLVER_NUM_ITERATIONS 4

#define CONTACT_MANIFOLD_SIMPLE_KEYS

#define PHYSCONTACT_PENETRATION_SLOP 0.05f
#define PHYSCONTACT_BAUMGARTE_BIAS   0.4f
#define PHYSCONTACT_RESTITUTION_THRESHOLD -1.f

#define PHYSISLAND_AABB_EXPAND_BY_VELOCITY
#define PHYSISLAND_AABB_EXTRA_SPACE 0.2f

/*#ifndef PHYSICS_CONTACT_SOLVER_ITERATIONS
	#define PHYSICS_CONTACT_SOLVER_ITERATIONS 5
#endif*/


#endif