#ifndef settingsMemory_h
#define settingsMemory_h


#define MEMORY_KIBIBYTE 1024
#define MEMORY_MEBIBYTE (1024 * MEMORY_KIBIBYTE)

// Define the number of bytes to allocate for the memory manager.
#define MEMORY_HEAPSIZE (64 * MEMORY_MEBIBYTE)

#define MEMORY_USE_GLOBAL_MANAGER
#define MEMORY_USE_MODULE_MANAGER

//#define MEMORYREGION_EXTEND_ALLOCATORS
#define MEMORYREGION_EXTEND_MANAGERS

#define MEMPOOL_COUNT_USED_BLOCKS
#define MEMFREELIST_COUNT_USED_BLOCKS
#define MEMSINGLELIST_COUNT_USED_BLOCKS
#define MEMDOUBLELIST_COUNT_USED_BLOCKS
#define MEMQUADLIST_COUNT_USED_BLOCKS

// Define the base pool sizes for our object allocators!
#define MEMORY_MODULE_NUM_COMMANDS            128
#define MEMORY_MODULE_NUM_TEXTURES            36
#define MEMORY_MODULE_NUM_TEXGROUPS           3
#define MEMORY_MODULE_NUM_SKELETONS           2
#define MEMORY_MODULE_NUM_SKELEANIMDEFS       2
#define MEMORY_MODULE_NUM_SKELEANIMS          2
#define MEMORY_MODULE_NUM_MODELS              2
#define MEMORY_MODULE_NUM_PHYSCONTACTPAIRS    15//1
#define MEMORY_MODULE_NUM_PHYSSEPARATIONPAIRS 30//1
#define MEMORY_MODULE_NUM_PHYSJOINTPAIRS      1
#define MEMORY_MODULE_NUM_AABBNODES           11//3
#define MEMORY_MODULE_NUM_PHYSCOLLIDERS       12//4
#define MEMORY_MODULE_NUM_PHYSRIGIDBODYDEFS   3///2
#define MEMORY_MODULE_NUM_PHYSRIGIDBODIES     6//2
#define MEMORY_MODULE_NUM_OBJECTDEFS          4///3
#define MEMORY_MODULE_NUM_OBJECTS             7//3
#define MEMORY_MODULE_NUM_RENDERABLEDEFS      4///3
#define MEMORY_MODULE_NUM_RENDERABLES         7//3


#define MEMTREE_DEBUG


#endif